import Foundation

public extension DeviceModel.IPadModel {
    var name: String {
        switch self {
        // iPads
        case .gen1Wifi:                     return "iPad 1G (Wifi)"
        case .gen1Cellular:                 return "iPad 1G (Cellular)"
        case .gen2Wifi:                     return "iPad 2G (Wifi)"
        case .gen2GSM:                      return "iPad 2G (GSM)"
        case .gen2CDMA:                     return "iPad 2G (CDMA)"
        case .gen2NewRev:                   return "iPad 2G (NewRev)"
        case .gen3Wifi:                     return "iPad 3G (Wifi)"
        case .gen3CDMA:                     return "iPad 3G (CDMA)"
        case .gen3GSM:                      return "iPad 3G (GSM)"
        case .gen4Wifi:                     return "iPad 4G (Wifi)"
        case .gen4GSM:                      return "iPad 4G (GSM)"
        case .gen4CDMA:                     return "iPad 4G (CDMA)"
        case .gen5Wifi:                     return "iPad 5G (Wifi)"
        case .gen5Cellular:                 return "iPad 5G (Cellular)"
        case .gen6Wifi:                     return "iPad 6G (Wifi)"
        case .gen6Cellular:                 return "iPad 6G (Cellular)"
        case .gen7Wifi:                     return "iPad 7G (Wifi)"
        case .gen7Cellular:                 return "iPad 7G (Cellular)"
        case .gen8Wifi:                     return "iPad 8G (Wifi)"
        case .gen8Cellular:                 return "iPad 8G (Cellular)"
        case .gen9Wifi:                     return "iPad 9G (Wifi)"
        case .gen9Cellular:                 return "iPad 9G (Cellular)"
        case .gen10Wifi:                    return "iPad 10G (Wifi)"
        case .gen10Cellular:                return "iPad 10G (Cellular)"
        case .gen11Wifi:                    return "iPad 11G (Wifi)"
        case .gen11Cellular:                return "iPad 11G (Cellular)"
            
        // Minis
        case .mini1Wifi:                    return "iPad Mini 1 (Wifi)"
        case .mini1GSM:                     return "iPad Mini 1 (GSM)"
        case .mini1CDMA:                    return "iPad Mini 1 (CDMA)"
        case .mini2Wifi:                    return "iPad Mini 2 (Wifi)"
        case .mini2GSMCDMA:                 return "iPad Mini 2 (Cellular)"
        case .mini2China:                   return "iPad Mini 2 (China)"
        case .mini3Wifi:                    return "iPad Mini 3 (Wifi)"
        case .mini3GSMCDMA:                 return "iPad Mini 3 (Cellular)"
        case .mini3China:                   return "iPad Mini 3 (China)"
        case .mini4Wifi:                    return "iPad Mini 4 (Wifi)"
        case .mini4Cellular:                return "iPad Mini 4 (Cellular)"
        case .mini5Wifi:                    return "iPad Mini 5 (Wifi)"
        case .mini5Cellular:                return "iPad Mini 5 (Cellular)"
        case .mini6Wifi:                    return "iPad Mini 6 (Wifi)"
        case .mini6Cellular:                return "iPad Mini 6 (Cellular)"
        case .miniA17ProWifi:               return "iPad Mini A17 Pro (Wifi)"
        case .miniA17ProCellular:           return "iPad Mini A17 Pro (Cellular)"
            
        // Airs
        case .air1Wifi:                     return "iPad Air 1 (Wifi)"
        case .air1GSMCDMA:                  return "iPad Air 1 (Cellular)"
        case .air1China:                    return "iPad Air 1 (China)"
        case .air2Wifi:                     return "iPad Air 2 (Wifi)"
        case .air2Cellular:                 return "iPad Air 2 (Cellular)"
        case .air3Wifi:                     return "iPad Air 3 (Wifi)"
        case .air3Cellular:                 return "iPad Air 3 (Cellular)"
        case .air4Wifi:                     return "iPad Air 4 (Wifi)"
        case .air4Cellular:                 return "iPad Air 4 (Cellular)"
        case .air5Wifi:                     return "iPad Air 5 (Wifi)"
        case .air5Cellular:                 return "iPad Air 5 (Cellular)"
        case .air11InchM2Wifi:              return "iPad Air M2 11\" (Cellular)"
        case .air11InchM2Cellular:          return "iPad Air M2 11\" (Cellular)"
        case .air13InchM2Wifi:              return "iPad Air M2 13\" (Wifi)"
        case .air13InchM2Cellular:          return "iPad Air M2 13\" (Cellular)"
        case .air11InchM3Wifi:              return "iPad Air M3 11\" (Wifi)"
        case .air11InchM3Cellular:          return "iPad Air M3 11\" (Cellular)"
        case .air13InchM3Wifi:              return "iPad Air M3 13\" (Wifi)"
        case .air13InchM3Cellular:          return "iPad Air M3 13\" (Cellular)"

        // Pros
        case .pro1_9d7inchWifi:             return "iPad Pro 1G 9.7\" (Wifi)"
        case .pro1_9d7inchCellular:         return "iPad Pro 1G 9.7\" (Cellular)"
        case .pro1_12d9inchWifi:            return "iPad Pro 1G 12.9\" (Wifi)"
        case .pro1_12d9inchCellular:        return "iPad Pro 1G 12.9\" (Cellular)"
        case .pro1_10d5inchWifi:            return "iPad Pro 1G 10.5\" (Wifi)"
        case .pro1_10d5inchCellular:        return "iPad Pro 1G 10.5\" (Cellular)"
        case .pro2_12d9inchWifi:            return "iPad Pro 2G 12.9\" (Wifi)"
        case .pro2_12d9inchCellular:        return "iPad Pro 2G 12.9\" (Cellular)"
        case .pro1_11inchWifi:              return "iPad Pro 1G 11\" (Wifi)"
        case .pro1_11inchWifiTera:          return "iPad Pro 1G 11\" (Wifi + Tera)"
        case .pro1_11inchCellular:          return "iPad Pro 1G 11\" (Cellular)"
        case .pro1_11inchCellularTera:      return "iPad Pro 1G 11\" (Cellular + Tera)"
        case .pro2_11inchWifi:              return "iPad Pro 2G 11\" (Wifi)"
        case .pro2_11inchCellular:          return "iPad Pro 2G 11\" (Cellular)"
        case .pro3_12d9inchWifi:            return "iPad Pro 3G 12.9\" (Wifi)"
        case .pro3_12d9inchWifiTera:        return "iPad Pro 3G 12.9\" (Wifi + Tera)"
        case .pro3_12d9inchCellular:        return "iPad Pro 3G 12.9\" (Cellular)"
        case .pro3_12d9inchCellularTera:    return "iPad Pro 3G 12.9\" (Cellular + Tera)"
        case .pro4_12d9inchWifi:            return "iPad Pro 4G 12.9\" (Wifi)"
        case .pro4_12d9inchCellular:        return "iPad Pro 4G 12.9\" (Cellular)"
        case .pro3_11inchWifi:              return "iPad Pro 3G 11\" (Wifi)"
        case .pro3_11inchWifiTera:          return "iPad Pro 3G 11\" (Wifi + Tera)"
        case .pro3_11inchCellular:          return "iPad Pro 3G 11\" (Cellular)"
        case .pro3_11inchCellularTera:      return "iPad Pro 3G 11\" (Cellular + Tera)"
        case .pro5_12d9inchWifi:            return "iPad Pro 5G 12.9\" (Wifi)"
        case .pro5_12d9inchWifiTera:        return "iPad Pro 5G 12.9\" (Wifi + Tera)"
        case .pro5_12d9inchCellular:        return "iPad Pro 5G 12.9\" (Cellular)"
        case .pro5_12d9inchCellularTera:    return "iPad Pro 5G 12.9\" (Cellular + Tera)"
        case .pro4_11inchWifi:              return "iPad Pro 4G 11\" (Wifi)"
        case .pro4_11inchCellular:          return "iPad Pro 4G 11\" (Cellular)"
        case .pro6_12d9inchWifi:            return "iPad Pro 6G 12.9\" (Wifi)"
        case .pro6_12d9inchCellular:        return "iPad Pro 6G 12.9\" (Cellular)"
        case .pro_11inchM4Wifi:              return "iPad Pro 7G 11\" (Wifi)"
        case .pro_11inchM4Cellular:          return "iPad Pro 7G 11\" (Cellular)"
        case .pro_13inchM4Wifi:              return "iPad Pro 7G 13\" (Wifi)"
        case .pro_13inchM4Cellular:          return "iPad Pro 7G 13\" (Cellular)"
        }
    }
}
